title:              Simon Woodward - personal blog
tagline:            A place to document, for myself, the things I figure out.
description:        
url:                http://seamonstr.github.io

author:
  name:             Simon Woodward 
  url:              https://twitter.com/seamonstr
  email:            simon@redcabbage.org

# GitHub Pages / Jekyll configuration
baseurl:            ''
gems: [jekyll-paginate]
permalink:          /:title/
paginate:           5
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post

theme: jekyll-theme-minimal

# Embedded comments
talkyard_server_url: https://site-82fqiczdy1.talkyard.net
talkyard_script_url: https://c1.ty-cdn.net/-/talkyard-comments.min.js